name: Bump version

on:
  repository_dispatch:
    types:
      - release

jobs:
  bump:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Bump version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./update.sh ${{ github.event.client_payload.ref }}
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Bump version"
          git push origin main

      - name: Push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag ${{ github.event.client_payload.ref }}
          git push origin ${{ github.event.client_payload.ref }}
